version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: casf
      POSTGRES_USER: casf
      POSTGRES_PASSWORD: casf
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  verifier:
    build: ../../services/verifier
    environment:
      PG_DSN: "dbname=casf user=casf password=casf host=postgres port=5432"
    depends_on:
      - postgres
    ports:
      - "8088:8000"
